# Generated by Django 3.2 on 2022-12-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
