# Generated by Django 3.2 on 2022-11-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.IntegerField(choices=[(0, 'DiscountNo'), (1, 'DiscountYes')], default='0'),
        ),
    ]
